[package]
name = "opencut-desktop"
description = "OpenCut desktop app, built with GPUI"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "opencut-desktop"
path = "src/main.rs"

[dependencies]
clip-finder = { workspace = true }
clips = { workspace = true }
gpui = { workspace = true }
ids = { workspace = true }
serde_json = "1"
time = { workspace = true }
timelines = { workspace = true }
